### ISSUE TITLE
Maybe we need to add a method isNetworkAvailable() to the library

### ISSUE THREAD

**Issue by contrudar** [TouchInstinct/RoboSwag-components#26]
public boolean isNetworkAvailable() {
        final ConnectivityManager connectivityManager = (ConnectivityManager) this.getSystemService(Context.CONNECTIVITY_SERVICE);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            final Network[] networks = connectivityManager.getAllNetworks();
            for (final Network network : networks) {
                final NetworkInfo networkInfo = connectivityManager.getNetworkInfo(network);
                if (networkInfo != null && (networkInfo.getState().equals(NetworkInfo.State.CONNECTED)
                        || networkInfo.getState().equals(NetworkInfo.State.CONNECTING))) {
                    return true;
                }
            }
        } else {
            return isNetworkAvailableOnPreLollipop(connectivityManager);
        }
        return false;
    }

private boolean isNetworkAvailableOnPreLollipop(@NonNull final ConnectivityManager connectivityManager) {
        //noinspection deprecation
        final NetworkInfo[] networkInfos = connectivityManager.getAllNetworkInfo();
        if (networkInfos != null) {
            for (final NetworkInfo networkInfo : networkInfos) {
                if (networkInfo.getState() == NetworkInfo.State.CONNECTED || networkInfo.getState() == NetworkInfo.State.CONNECTING) {
                    return true;
                }
            }
        }
        return false;
    }

**Comment by ZuZuK** [comment]
will be in templates
